### ISSUE TITLE
LD error due to missing "-lboost_filesystem"

### ISSUE THREAD

**Issue by cburschka** [Malvineous/libgamearchive#4]
While making `./examples/gamearchive`, I get the following error:

```
  CXXLD    gamearch
/usr/bin/ld: gamearch.o: undefined reference to symbol '_ZN5boost10filesystem6detail16create_directoryERKNS0_4pathEPNS_6system10error_codeE'
//usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.54.0: error adding symbols: DSO missing from command line
```

Unfortunately, `env LDFLAGS="-lboost_filesystem" make` didn't do the trick, but I was able to get rid of the error by changing the Makefile directly. Not sure why automake goes wrong here.

``` diff
AM_LDFLAGS = $(top_builddir)/src/libgamearchive.la $(BOOST_LDFLAGS) \
-   $(BOOST_SYSTEM_LIB) $(BOOST_PROGRAM_OPTIONS_LIB) \
+   $(BOOST_SYSTEM_LIB) $(BOOST_FILESYSTEM_LIB) $(BOOST_PROGRAM_OPTIONS_LIB) \

    $(libgamecommon_LIBS)
```

**Comment by Malvineous** [comment]
How strange!  I've compiled that for years without error and never noticed that I forgot to include the library - how it has been working up until now I have no idea!  Fixed in commit e71e9c702493283a95cc499e6e1d222e2fabf0cd.  Many thanks for the report.
